server {
    listen 80;
    listen [::]:80;
    server_name alco-helper.ru www.alco-helper.ru;
    server_tokens off;
    add_header X-Robots-Tag "noindex, nofollow, noarchive" always;
    return 301 https://alco-helper.ru$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name www.alco-helper.ru;
    server_tokens off;

    ssl_certificate /var/www/httpd-cert/www-root/migration-services-san.fullchain.crt;
    ssl_certificate_key /var/www/httpd-cert/www-root/migration-services-san.key;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Robots-Tag "noindex, nofollow, noarchive" always;
    return 301 https://alco-helper.ru$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name alco-helper.ru;
    server_tokens off;

    ssl_certificate /var/www/httpd-cert/www-root/migration-services-san.fullchain.crt;
    ssl_certificate_key /var/www/httpd-cert/www-root/migration-services-san.key;

    client_max_body_size 1m;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Robots-Tag "noindex, nofollow, noarchive" always;

    location / {
        proxy_pass http://127.0.0.1:777;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 180s;
        proxy_send_timeout 180s;
        proxy_connect_timeout 10s;
    }
}
